spring.application.name=demo-website-tramhuong
spring.datasource.url=jdbc:mysql://localhost:3306/tramhuong_api
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

jwt.secret = dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS1mb3Itand0LXNpZ25pbmctbGUtMjU2LWJpdHM=
jwt.expiration = 3600000